# Generated by Django 3.2.13 on 2022-06-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showplace', '0003_auto_20220603_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showplace',
            options={'ordering': ('name', 'category')},
        ),
    ]
