# Generated by Django 3.2.13 on 2022-06-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showplace', '0007_alter_showplace_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showplace',
            options={'ordering': ('name', 'category')},
        ),
    ]
