# Generated by Django 3.2.13 on 2022-06-02 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('showplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showplace',
            name='sh_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
