# Generated by Django 3.2.13 on 2022-06-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showplace', '0004_alter_showplace_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Showplace',
        ),
    ]
