# Generated by Django 3.2.13 on 2022-06-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showplace', '0006_showplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showplace',
            name='category',
            field=models.CharField(max_length=128),
        ),
    ]
