# Generated by Django 3.2.13 on 2022-06-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showplace', '0010_alter_showplace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showplace',
            options={},
        ),
        migrations.AlterField(
            model_name='showplace',
            name='category',
            field=models.CharField(max_length=128),
        ),
    ]
