# Generated by Django 3.2.13 on 2022-06-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category'),
        ('showplace', '0011_auto_20220603_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showplace',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
