# Generated by Django 3.2.13 on 2022-06-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showplace', '0012_alter_showplace_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showplace',
            old_name='category',
            new_name='category_id',
        ),
    ]
