# Generated by Django 3.2.13 on 2022-06-03 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showplace', '0009_auto_20220603_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showplace',
            options={'ordering': ('name', 'category')},
        ),
    ]
